name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
         conda create -q -y --name testenv python=3.8 cython numpy pytest psutil pip
         conda install -c conda-forge pip numpy scipy coverage scikit-learn!=0.19.0 matplotlib numba ffmpeg libsndfile pysoundfile coveralls
    - name: Test with pytest
      run: |
        conda install pytest
        pip3 install wrapt
        pip3 install wget
        pip3 install torch
        pip3 install onnx
        pip3 install omegaconf
        pip3 install librosa
        pip3 install hydra-core
        pip3 install pytorch_lightning
        pip3 install pandas
        pip3 install frozendict
        pip3 install braceexpand
        pip3 install inflect 
        pip3 install webdataset
        pip3 install unidecode
        pip3 install h5py
        pip3 install transformers
        pip3 install sentencepiece 
        pip3 install editdistance
        pip3 install rapidfuzz 
        pip3 install pesq
        pip3 install youtokentome 
        pip3 install pystoi
        pip3 install sacrebleu 
        pip3 install Cython
        pip3 install nltk
        pip3 install jieba
        pip3 install opencc
        pip3 install pangu
        pytest
